<?php 
// get it's configuration file
$site = new Zend_Config_Ini(APPLICATION_PATH . '/configs/site.ini', APPLICATION_ENV);

$this->placeholder('header')->captureStart(); ?>
<div id="SiteName">
    <h1><?php echo $site->name; ?></h1>
</div>

<div id="Slogan">
    <small><?php echo $site->slogan; ?></small>
</div><?php $this->placeholder('header')->captureEnd(); ?>
<?php echo $this->placeholder('header')->setIndent(16); ?>
